### ISSUE TITLE
UnionFind-Implementation

### ISSUE THREAD

**Issue by kittobi1992** [pjungeblut/ChaosKITs#10]
Is it necassary to store parent and size seperat? I remember and implementation where you store the negative size of each subset in the root node e.g. parent[root] = -size and for each child c of this root node you store parent[c] = root (or another child in this subset)

**Comment by pjungeblut** [comment]
I guess such an implementation is possible. But does it make things simpler?
I don't see any gains except a little bit of memory.

**Comment by kittobi1992** [comment]
you can code it faster, because you don't have to update two vectors.

**Comment by pjungeblut** [comment]
Feel free to update, but add a coment that explains the used trick.

**Comment by kittobi1992** [comment]
I've added unionFind2.cpp to the datastructures folder. It's very similiar to the old implementation, but much faster. For a sample problem on UVA I've received 33% better runtime with this implementation. You can decide what implementation should be further used.

PS: I think the other implementation is wrong, because the size vector is not updated all the time if you link two subsets.

**Comment by kittobi1992** [comment]
Maybe the better runtime is caused by the fact that in the old implementation the size vector is updated wrong

**Comment by pjungeblut** [comment]
Ok, I see what you mean. First of all, my implementation is correct!!!!! :P 

What I have to agree on: The variable name `size` is misleading though. Actually what you are doing is "union by size", what I am doing is "union by rank". So `size` in my code is actually not the size of the tree but an upper bound on the height of the tree. That's why I only update `size` when really increasing the size of the tree.

To get the proof for the runtime working, you need to do "union by rank". This is the reason why I would like to keep it with "union by rank". Even though your implementation might be faster in this task. In praxis this all shouldn't matter, since it's all (nearly) constant time per lookup.

But: Saving some memory might be a good anyways, so storing the rank in the parent array. If you are ok with that, I will implement a solution using only one array and union by rank.

PS: I guess the initial reason why it's called size and not rank is, that rank is a reserved name and can't be used with some compiler options.

**Comment by pjungeblut** [comment]
Just tried the more memory efficient solution: Doesn't really affect runtime, it should  always be fast enough with the two vectors. I don't really want to merge them, because it's harder to understand then.

Anyway, I changed the variable name `size` to `height`.
